/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/_dashboard'
import { Route as AdminLoginIndexRouteImport } from './routes/admin/login/index'
import { Route as AdminDashboardDashboardIndexRouteImport } from './routes/admin/_dashboard/dashboard/index'
import { Route as AdminDashboardDashboardCreateElectionRouteImport } from './routes/admin/_dashboard/dashboard/create-election'
import { Route as AdminDashboardDashboardElectionsIndexRouteImport } from './routes/admin/_dashboard/dashboard/elections/index'
import { Route as AdminDashboardDashboardElectionsElectionIdDetailsRouteImport } from './routes/admin/_dashboard/dashboard/elections/$electionId/details'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginIndexRoute = AdminLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardDashboardIndexRoute =
  AdminDashboardDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardDashboardCreateElectionRoute =
  AdminDashboardDashboardCreateElectionRouteImport.update({
    id: '/dashboard/create-election',
    path: '/dashboard/create-election',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardDashboardElectionsIndexRoute =
  AdminDashboardDashboardElectionsIndexRouteImport.update({
    id: '/dashboard/elections/',
    path: '/dashboard/elections/',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardDashboardElectionsElectionIdDetailsRoute =
  AdminDashboardDashboardElectionsElectionIdDetailsRouteImport.update({
    id: '/dashboard/elections/$electionId/details',
    path: '/dashboard/elections/$electionId/details',
    getParentRoute: () => AdminDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminDashboardRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/admin/login': typeof AdminLoginIndexRoute
  '/admin/dashboard/create-election': typeof AdminDashboardDashboardCreateElectionRoute
  '/admin/dashboard': typeof AdminDashboardDashboardIndexRoute
  '/admin/dashboard/elections': typeof AdminDashboardDashboardElectionsIndexRoute
  '/admin/dashboard/elections/$electionId/details': typeof AdminDashboardDashboardElectionsElectionIdDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminDashboardRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/admin/login': typeof AdminLoginIndexRoute
  '/admin/dashboard/create-election': typeof AdminDashboardDashboardCreateElectionRoute
  '/admin/dashboard': typeof AdminDashboardDashboardIndexRoute
  '/admin/dashboard/elections': typeof AdminDashboardDashboardElectionsIndexRoute
  '/admin/dashboard/elections/$electionId/details': typeof AdminDashboardDashboardElectionsElectionIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_dashboard': typeof AdminDashboardRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/admin/login/': typeof AdminLoginIndexRoute
  '/admin/_dashboard/dashboard/create-election': typeof AdminDashboardDashboardCreateElectionRoute
  '/admin/_dashboard/dashboard/': typeof AdminDashboardDashboardIndexRoute
  '/admin/_dashboard/dashboard/elections/': typeof AdminDashboardDashboardElectionsIndexRoute
  '/admin/_dashboard/dashboard/elections/$electionId/details': typeof AdminDashboardDashboardElectionsElectionIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/login'
    | '/admin/dashboard/create-election'
    | '/admin/dashboard'
    | '/admin/dashboard/elections'
    | '/admin/dashboard/elections/$electionId/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/login'
    | '/admin/dashboard/create-election'
    | '/admin/dashboard'
    | '/admin/dashboard/elections'
    | '/admin/dashboard/elections/$electionId/details'
  id:
    | '__root__'
    | '/'
    | '/admin/_dashboard'
    | '/login/'
    | '/admin/login/'
    | '/admin/_dashboard/dashboard/create-election'
    | '/admin/_dashboard/dashboard/'
    | '/admin/_dashboard/dashboard/elections/'
    | '/admin/_dashboard/dashboard/elections/$electionId/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_dashboard': {
      id: '/admin/_dashboard'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login/': {
      id: '/admin/login/'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_dashboard/dashboard/': {
      id: '/admin/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/_dashboard/dashboard/create-election': {
      id: '/admin/_dashboard/dashboard/create-election'
      path: '/dashboard/create-election'
      fullPath: '/admin/dashboard/create-election'
      preLoaderRoute: typeof AdminDashboardDashboardCreateElectionRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/_dashboard/dashboard/elections/': {
      id: '/admin/_dashboard/dashboard/elections/'
      path: '/dashboard/elections'
      fullPath: '/admin/dashboard/elections'
      preLoaderRoute: typeof AdminDashboardDashboardElectionsIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/_dashboard/dashboard/elections/$electionId/details': {
      id: '/admin/_dashboard/dashboard/elections/$electionId/details'
      path: '/dashboard/elections/$electionId/details'
      fullPath: '/admin/dashboard/elections/$electionId/details'
      preLoaderRoute: typeof AdminDashboardDashboardElectionsElectionIdDetailsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
